# Generated by Django 3.1.7 on 2021-03-06 05:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model_class',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
    ]
